Poller/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('auth.urls')),
    path('',include('main.urls'))
]

auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
    path('login/',views.Login.as_view(),name='auth_login'),
    path('logout/',views.Logout.as_view(),name='auth_logout')
        ]

main/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from main import views


urlpatterns = [
 path('', views.Index.as_view(), name='index'),
 #path('question/<int:pk>', views.Question.as_view(), name ='question')
 path('question/<slug>',login_required(views.Question.as_view()), name ='question')

#slug makes the url usr readable 
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    slug = models.SlugField()
    content = models.CharField(max_length = 1024)

    def __str__(self):
        return self.content

class Answer(models.Model):
    question = models.ForeignKey('Question',on_delete = models.CASCADE)
    choice = models.ForeignKey('choice',on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete = models.CASCADE)       

class Choice(models.Model):
    question = models.ForeignKey('Question',on_delete = models.CASCADE)
    content = models.CharField(max_length = 256)

    @property #property decorator we need not to call the function
    def answer_count(self):
            return Answer.objects.filter(
            question=self.question,
            choice = self
            ).count()

    
    def __str__(self):
        return "{} - {}".format(self.question.content[:50],self.content)

    

main/forms.py
from django import forms

from main import models

class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [ 'choice' ]

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    FormView
)
from django.views.generic.detail import BaseDetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
#mixin dont handle views jus overwrites the sigleobject data
from main import models, forms
# Create your views here.

class Index(ListView):
 model = models.Question
 template_name = 'main/index.html'

class Question(PermissionRequiredMixin, BaseDetailView,FormView):
  model = models.Question
  template_name = 'main/components/question.html'
  form_class = forms.AnswerForm
  permission_required = 'add_answer'
#adding anwers to generic views
  def get_context_data(self,**kwargs):
      data = super().get_context_data(**kwargs)
      data['answer'] = models.Answer.objects.get(
          question = self.get_object(),
          user = self.request.user
      )  
      return data
#adding funcionality of current logged in users
  def form_valid(self,form):
     obj = form.save(commit = False)
     obj.question = self.get_object()
     obj.user = self.request.user
     obj.user = self.request.user
     obj.save()

     return HttpResponseRedirect('/')

  def post(self, request ,*args,**kwargs):
      self.object = self.get_object()
      return super().post(request , *args, **kwargs)   

  def get(self, request,*args, **kwargs):
     self.object = self.get_object()
     context = self.get_context_data(object=self.object)
     return self.render_to_response(context)

templates/main/components/navbar.html
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Poller</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Questions</a></li>
        <li>
          {% if request.user.is_authenticated %}
           <a href="{% url 'auth_logout' %}">Logout</a>
          {% else %}
          <a href="{% url 'auth_login' %}">Login</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </nav>
        

templates/main/components/question.html
{% extends 'auth/base.html' %}

{% block content %}

{% include 'main/components/navbar.html' %}

<div class="container">
<div class="row">
    <h4>{{ question.content }}</h4>
</div>

<form action="" method="POST">
  {% csrf_token %}  

  <div class="row">
      <div class="col-6">
          <div class="collection">
            {% for choice in question.choice_set.all %}
             <div class="collection-item"> 
               {% if answer %}
                  {{choice.content}} ({{choice.answer_count}})
                  {% if answer.choice.id == choice.id %}
                    <i class="material-icons">check</i>
                  {% endif %}
               {% else %}     
                 <label>
                    <input class="with-gap" name="choice" type="radio" value="{{choice.id}}" />
                    <span>{{ choice.content }}</span>
                 </label>
               {% endif %} 
             </div>
            {% endfor %}
          </div>
      </div>
  </div>
 {% if answer %}
 <div class="row">
     <button class="btn waves-effect waves-light" type="submit" name="action">
         Submit
         <i class="material-icons right"></i>
     </button>
   </div>
 {% endif %} 

 <div class="row">
    <p class="red">
      <ul> 
        {% for error in form.error %}
        <li>
          {{error}}
        </li>  
        {% endfor %}  
      </ul>
    </p>
 </div>
</form> 
</div>

{% endblock %}

templates/main/index.html
{% extends 'auth/base.html' %}

{% block content %}

 {% include 'main/components/navbar.html' %}

 <div class="container">
<div class="row">
    <h4>Trending Questions</h4>

</div>

  <div class="row">
      <div class="col-6">
          <div class="collection">
              {% for question in question_list %}
              <a href="{% url 'question' question.slug %}" class="collection-item">
               {{ question.content }}
            </a>
              {% endfor %}
          </div>
      </div>
  </div>
</div>
  

{% endblock %}